Add edit button
A11yship/capstone-project pull request #29
Opened 2022-09-02 14:10 UTC by A11yship

2022-09-03 18:44 UTC, UniversalTraveller commented on src/pages/create-task.js
> +	console.log(query.id);
Please remove all console.log() from the final code.

2022-09-03 18:48 UTC, UniversalTraveller commented
Hi Hannah, cheers to a fellow Saturday night coder! 🥂  The PR looks good to me. Just found one console.log that should better be deleted.

2022-09-05 09:42 UTC, aclaes requested changes

2022-09-05 09:42 UTC, aclaes commented on src/components/Form/Form.js
> +		task.id ? editTask(task.id, taskName, duration) : addTask(taskName, duration);
You would use the ternary operator only if value es generated - which is not the case here (like: `const myVar = ...? ... : ...`)

Please use an if-else-block

2022-09-05 13:01 UTC, merged